load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "OneValueReader",
    srcs = ["OneValueReader.cpp"],
    hdrs = ["OneValueReader.h"],
    deps = [
        "//task/Reader:Reader",       
    ],
    visibility = ["//visibility:public"],
)

