load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "DataStore",
    srcs = ["DataStore.cpp"],
    hdrs = ["DataStore.h"],
    deps = [
        "//task/main:opencv",
        "//task/Types:Types",       
    ],
    visibility = ["//visibility:public"],     
)

