load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ImageReader",
    srcs = ["ImageReader.cpp"],
    hdrs = ["ImageReader.h"],
    deps = [
        "//task/Reader:Reader",       
    ],
    visibility = ["//visibility:public"],
)

