load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "Types",
    srcs = ["Types.cpp"],
    hdrs = ["Types.h"],
    deps = [
        "//task/main:local",
        "//task/main:opencv",
    ],
    visibility = ["//visibility:public"],
)

