load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ClockManger",
    srcs = ["ClockManger.cpp"],
    hdrs = ["ClockManger.h"],
    deps = [
        "//task/main:opencv",
    ],
    visibility = ["//visibility:public"],
)

