load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "GpsReader",
    srcs = ["GpsReader.cpp"],
    hdrs = ["GpsReader.h"],
    deps = [
        "//task/Reader:Reader",       
    ],
    visibility = ["//visibility:public"],
)

